export interface POITranslation {
  id?: number;
  poiId?: number;
  languageCode: string;
  name: string;
  content: string;
  audioUrl?: string;
  approvalStatus?: string;
  approvedById?: number;
  approvedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  isAutoGenerated?: boolean;
}

export interface POI {
  id: number;
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  radiusMeters: number;
  priority: number;
  imageUrl?: string;
  audioUrl?: string;
  contentJson?: string;
  googleMapsUrl?: string;
  createdAt: string;
  updatedAt: string;
  viewCount: number;
  status: string;
  restaurantOwnerId?: number;
  translations: POITranslation[];
}

export interface CreatePOI {
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  radiusMeters?: number;
  priority?: number;
  imageUrl?: string;
  restaurantOwnerId?: number;
  translations?: CreatePOITranslation[];
}

export interface CreatePOITranslation {
  languageCode: string;
  name: string;
  content: string;
}

export interface UpdatePOI {
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  radiusMeters: number;
  priority: number;
  imageUrl?: string;
  status: string;
}

export interface Narration {
  id: number;
  poiId: number;
  poiName: string;
  userId: string;
  languageCode: string;
  playedAt: string;
  narratType: string;
  userLatitude: number;
  userLongitude: number;
  distanceMeters: number;
}

export interface LocationUpdate {
  userId: string;
  latitude: number;
  longitude: number;
  accuracy: number;
  timestamp: string;
}

export interface MenuItem {
  id: number;
  poiId: number;
  name: string;
  description?: string;
  price: number;
  imageUrl?: string;
  isAvailable: boolean;
}

export interface CreateMenuItem {
  name: string;
  description?: string;
  price: number;
  imageUrl?: string;
  isAvailable?: boolean;
}

export interface Review {
  id: number;
  poiId: number;
  poiName: string;
  userName: string;
  rating: number;
  comment?: string;
  createdAt: string;
}

export interface CreateReview {
  userName?: string;
  rating: number;
  comment?: string;
}

export interface TourStop {
  id: number;
  order: number;
  customDescription?: string;
  poi?: POI;
}

export interface Tour {
  id: number;
  name: string;
  description: string;
  imageUrl?: string;
  durationMinutes: number;
  distanceKm: number;
  status: string;
  stopCount: number;
  stops: TourStop[];
}

export interface TourStopRequest {
  poiId: number;
  order: number;
  customDescription?: string;
}

export interface CreateTourRequest {
  name: string;
  description: string;
  imageUrl?: string;
  durationMinutes: number;
  distanceKm: number;
  stops?: TourStopRequest[];
}
