import React, { useState } from 'react';
import { Modal, Table, Button, Space, Tag, message, Tooltip, Select } from 'antd';
import { EditOutlined, DeleteOutlined, PlusOutlined, SoundOutlined, CheckCircleOutlined, ClockCircleOutlined, RobotOutlined, UserOutlined } from '@ant-design/icons';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { translationApi } from '../services/api';
import type { POI, POITranslation } from '../types';
import TranslationForm from './TranslationForm';
import TTSPreview from './TTSPreview';

interface TranslationManagerProps {
  poi: POI;
  visible: boolean;
  onClose: () => void;
}

const TranslationManager: React.FC<TranslationManagerProps> = ({ poi, visible, onClose }) => {
  const queryClient = useQueryClient();
  const [editingTranslation, setEditingTranslation] = useState<POITranslation | null>(null);
  const [isFormVisible, setIsFormVisible] = useState(false);
  const [filterType, setFilterType] = useState<'all' | 'auto' | 'manual'>('all');

  const { data: translations, refetch } = useQuery({
    queryKey: ['translations', poi.id],
    queryFn: async () => {
      const response = await translationApi.getByPOI(poi.id);
      return response.data;
    },
    enabled: visible,
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => translationApi.delete(id),
    onSuccess: () => {
      message.success('Xóa translation thành công');
      refetch();
      queryClient.invalidateQueries({ queryKey: ['poi', poi.id] });
      queryClient.invalidateQueries({ queryKey: ['pois'] });
    },
    onError: () => {
      message.error('Xóa translation thất bại');
    },
  });

  const handleAddTranslation = () => {
    setEditingTranslation(null);
    setIsFormVisible(true);
  };

  const handleDelete = (id: number) => {
    Modal.confirm({
      title: 'Xác nhận xóa',
      content: 'Bạn có chắc chắn muốn xóa bản dịch này?',
      okText: 'Xóa',
      okType: 'danger',
      cancelText: 'Hủy',
      onOk: () => deleteMutation.mutate(id),
    });
  };

  const handleEditTranslation = (translation: POITranslation) => {
    setEditingTranslation(translation);
    setIsFormVisible(true);
  };

  const handleFormClose = () => {
    setIsFormVisible(false);
    setEditingTranslation(null);
    refetch();
  };

  const getLanguageFlag = (code: string) => {
    const flags: { [key: string]: string } = {
      'vi': '🇻🇳',
      'en': '🇺🇸',
      'ko': '🇰🇷',
      'ja': '🇯🇵',
      'zh': '🇨🇳',
    };
    return flags[code] || '🌐';
  };

  const getLanguageName = (code: string) => {
    const names: { [key: string]: string } = {
      'vi': 'Tiếng Việt',
      'en': 'English',
      'ko': '한국어',
      'ja': '日本語',
      'zh': '中文',
    };
    return names[code] || code;
  };

  const filteredTranslations = translations?.filter(t => {
    if (filterType === 'auto') return t.isAutoGenerated === true;
    if (filterType === 'manual') return !t.isAutoGenerated;
    return true;
  });

  const columns = [
    {
      title: 'Ngôn ngữ',
      dataIndex: 'languageCode',
      key: 'languageCode',
      width: 150,
      render: (code: string) => (
        <Space>
          <span style={{ fontSize: '20px' }}>{getLanguageFlag(code)}</span>
          <span>{getLanguageName(code)}</span>
        </Space>
      ),
    },
    {
      title: 'Tên POI',
      dataIndex: 'name',
      key: 'name',
      width: 200,
    },
    {
      title: 'Nguồn',
      dataIndex: 'isAutoGenerated',
      key: 'isAutoGenerated',
      width: 120,
      render: (isAuto: boolean) => (
        <Tag color={isAuto ? 'blue' : 'green'} icon={isAuto ? <RobotOutlined /> : <UserOutlined />}>
          {isAuto ? 'DeepL AI' : 'Manual'}
        </Tag>
      ),
    },
    {
      title: 'Nội dung thuyết minh',
      dataIndex: 'content',
      key: 'content',
      ellipsis: true,
      render: (content: string) => (
        <Tooltip title={content}>
          <div style={{ maxWidth: 300 }}>{content}</div>
        </Tooltip>
      ),
    },
    {
      title: 'Trạng thái',
      dataIndex: 'approvalStatus',
      key: 'approvalStatus',
      width: 120,
      render: (status: string) => {
        const config: { [key: string]: { color: string; icon: React.ReactNode; text: string } } = {
          'Approved': { color: 'green', icon: <CheckCircleOutlined />, text: 'Đã duyệt' },
          'Pending': { color: 'orange', icon: <ClockCircleOutlined />, text: 'Chờ duyệt' },
          'Rejected': { color: 'red', icon: <ClockCircleOutlined />, text: 'Từ chối' },
        };
        const { color, icon, text } = config[status] || config['Pending'];
        return (
          <Tag color={color} icon={icon}>
            {text}
          </Tag>
        );
      },
    },
    {
      title: 'Audio',
      key: 'audio',
      width: 100,
      render: (_: any, record: POITranslation) => (
        <TTSPreview 
          text={record.content} 
          languageCode={record.languageCode}
          buttonText="Nghe"
          buttonType="link"
        />
      ),
    },
    {
      title: 'Hành động',
      key: 'action',
      width: 150,
      render: (_: any, record: POITranslation) => (
        <Space size="small">
          <Button 
            type="link" 
            icon={<EditOutlined />} 
            onClick={() => handleEditTranslation(record)}
          >
            Sửa
          </Button>
          <Button 
            type="link" 
            danger 
            icon={<DeleteOutlined />} 
            onClick={() => handleDelete(record.id!)}
          >
            Xóa
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <>
      <Modal
        title={
          <Space>
            <SoundOutlined style={{ color: '#1890ff' }} />
            <span>Quản lý nội dung thuyết minh - {poi.name}</span>
          </Space>
        }
        open={visible}
        onCancel={onClose}
        footer={null}
        width={1200}
      >
        <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Space>
            <span style={{ color: '#666' }}>Lọc theo nguồn:</span>
            <Select
              value={filterType}
              onChange={setFilterType}
              style={{ width: 180 }}
              options={[
                { value: 'all', label: '🌐 Tất cả' },
                { value: 'auto', label: '🤖 DeepL AI' },
                { value: 'manual', label: '✍️ Manual' },
              ]}
            />
          </Space>
        </div>

        <Table
          columns={columns}
          dataSource={filteredTranslations || []}
          rowKey="id"
          pagination={false}
          size="small"
          locale={{
            emptyText: 'Chưa có nội dung thuyết minh. Translations sẽ được tự động tạo bởi DeepL AI khi người dùng truy cập.',
          }}
        />

        <div style={{ marginTop: '16px', padding: '12px', background: '#f0f7ff', borderRadius: '4px' }}>
          <p style={{ margin: 0, fontSize: '13px', color: '#666' }}>
            🤖 <strong>Auto-Translation:</strong> Hệ thống tự động dịch nội dung sang các ngôn ngữ khác bằng <strong>DeepL AI</strong> 
            khi người dùng truy cập lần đầu. Bạn có thể review và chỉnh sửa translations để đảm bảo chất lượng.
          </p>
          <p style={{ margin: '8px 0 0 0', fontSize: '13px', color: '#666' }}>
            💡 <strong>Lưu ý:</strong> Nội dung thuyết minh sẽ được phát tự động khi khách du lịch 
            vào trong bán kính {poi.radiusMeters}m của POI này.
          </p>
        </div>
      </Modal>

      <TranslationForm
        poi={poi}
        translation={editingTranslation}
        visible={isFormVisible}
        onClose={handleFormClose}
      />
    </>
  );
};

export default TranslationManager;
